**** HPMOR: Harry Potter and the Methods of Rationality

You can begin your study of the /Methods of Rationality/ enjoyably and
powerfully with the wonderful book [[http://www.hpmor.com][Harry Potter and the Methods of Rationality]],
often simply called HPMOR.

Frequently Asked Questions about HPMOR:
- How much does it cost? :: It's free!
- Where can I get it? :: Download it as an =epub=, =mobi= or =pdf= from [[https://github.com/rrthomas/hpmor/releases/tag/v1.2][Github]]
  and read it on your favorite device or read it online at [[http://www.hpmor.com][hpmor.com]].
- Is there a podcast? :: Yes, [[https://hpmorpodcast.com][hpmorpodcast.com]] or [[https://podcasts.apple.com/us/podcast/podcast-the-methods-of-rationality-podcast/id431784580][HPMOR itunes Podcast]].
- Is it available in other languages? :: You'll find translations into at least
  15 languages at [[http://www.hpmor.com/info][hpmor.com/info]]
- If any of those links is bad :: Check [[http://www.hpmor.com][hpmor.com]] for the latest content and links.
- Where did it come from? :: It was written by [[https://www.yudkowsky.net][Eliezer S. Yudkowsky]] who posted
  it to [[https://www.fanfiction.net/s/5782108/1/Harry_Potter_and_the_Methods_of_Rationality][the online FanFiction website]] as he wrote it from 28 February 2010 to 14
  March 2015.
- Do I have to be a Harry Potter Fan to "get" HPMOR? :: No you don't! However,
  for full value and enjoyment I recommend that you either watch [[https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone_(film)][the first Harry Potter
  Movie]] or read [[https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone][the first Harry Potter book]] before starting HPMOR.
- Do I have to read ALL of HPMOR? :: Eliezer recommends that you /read the first
  ten chapters of HPMOR/ and then decide whether it's for you. If at that point
  you're not "into it", it's probably not the right vehicle for you to learn the
  Methods of Rationality. Fortunately, there are other vehicles!
