* Rationality

A [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

** What Rationality Provides

Rationality is the art of
- making decisions that are in our best interest
- operating such that we produce the best outcomes for what we care about

** What Rationality Needs and Doesn't Provide

Study of Rationality and Mathematical Logic which it is based on will reveal
that there's nothing in either which can help us find or form
- the truth
- our goals
- our values
- our life purpose

Rationality does /NOT/ direct us to
- what we should care about

For the art of /discovering our best interests/ and /what we care about/
- see [[https://github.com/TouchPuuhonua/Deep-Rationality][Deep Rationality]]
- Rationality without Deep Rationality is irrational!

Rationality and Deep Rationality work together!

** Rationality Distinctions

The distinctions of /Rationality/ are extremely valuable
- Discovering what Reality offers
- Using valid reasoning about important issues
- Detecting Accidental and Malicious Fallacies
- and so forth

Rationality provides tools for determining if a reasoning process is valid or
invalid and whether, given a degree of confidence in the truth of the premises,
what degree of confidence would be justified in the conclusions.

The studying of Rationality is directed by our intellect with an awareness of
our emotions.  It is about the /integrity of our thinking/.

We face many challenges to acting Rationally, including
- Lack of awareness of our irrationality
- Insufficient Practice in the Art of Rationality
- Interference from Rhetorical Attacks

** Defense Against the Dark Arts of Rhetoric!

Power hierarchies are maintained by people who skillfully use [[https://en.wikipedia.org/wiki/Rhetoric][Rhetoric]] to
suppress your powers of discernment and manipulate your emotions. They are
trying to use you for their purposes. In their eyes you are
- A Worker-Consumer Unit
- A Subject, rather than a Citizen
- An NPC
- A Tool

This is not a new understanding. The More than 2000 years ago, the great
philosopher [[https://en.wikipedia.org/wiki/Socrates][Socrates]] taught about the misuse of [[https://en.wikipedia.org/wiki/Rhetoric][Rhetoric]] to persuade people to
believe things regardless of the truth of the matter.

Unethical use of Rhetoric is standard in
- Political Speech
- Commercial Marketing
- Where else in our world?

Learning and Practicing /The Methods of Rationality/ is a great help in
defending against clever and malicious use of Rhetoric.

*** The Methods of Rationality and HPMOR

The /Methods of Rationality/ are designed to
- Increase your ability to perceive what's going on
- Empower you to make good choices
- Detect when you're been fooled
      - By malicious others
      - By confusing situations
      - By your own mind!

There are many ways of learning the /Methods of Rationality/. Traditionally
learning the /Methods of Rationality/ has started with studying psychology and
logic and installing the methods into your life through practice.

A great new way of learning the /Methods of Rationality/ is by reading the
extraordinary and entertaining book [[file:hpmor.org][Harry Potter and the Methods of Rationality]]
which is available free from the website [[http://www.hpmor.com/info][hpmor.com]].

** Other Resources for Learning and Practicing the Methods of Rationality

The website [[https://www.lesswrong.com][lesswrong.com]] is full of wonderful resources for learning and
practicing the Methods of Rationality, including [[https://www.lesswrong.com/tag/sequences][the Sequences]], a coherent
introduction to Rationality, now also available as part of (another) book by
Eliezer Yudkowsky, [[https://www.lesswrong.com/tag/rationality:-from-ai-to-zombies][Rationality: From AI To Zombies]].

There are a number of excellent resources at the [[https://gregdavidson.github.io/loel][LOEL]] webpage
- [[https://gregdavidson.github.io/loel/loel-media.html][Extraordinary Learners: Books, Texts, Presentations, etc.]]

An excellent new book on Rationality is
- [[https://stevenpinker.com/publications/rationality-what-it-why-it-seems-so-scarce-and-why-it-matters][Rationality: What It Is, Why It Seems Scarce, Why It Matters]]
- by the incomparable [[https://en.wikipedia.org/wiki/Steven_Pinker][Steven Pinker]]

See our [[file:RESOUCES.org][Full List of Resources]] and please feel free to recommend others!

** This is the beginning of the LOEL Curriculum on Rationality

If you like the LOEL approach as described on our [[https://github.com/GregDavidson/loel#readme][LOEL Github Repository]] and the
[[https://gregdavidson.github.io/loel][Original LOEL Website]] and you like the idea of a powerful course on the Methods
of Rationality, please consider joining the team developing this course! You can
begin by getting a Github account and submitting an Issue to the LOEL Repository
or using Github to send a message to the repository owner.
