* Rationality

A [[https://github.com/GregDavidson/loel/blob/main/Devel/creating-curricula.org][Curriculum]] of the [[https://github.com/GregDavidson/loel#readme][League of Extraordinary Learners]].

** What Rationality Provides

Rationality is the art of
- making decisions that are in our best interest
- operating such that we produce the best outcomes for what we care about

** What Rationality Needs and Doesn't Provide

Rationality does /NOT/ direct us to
- the truth
- what we should care about

For the art of /discovering our best interests/ and /what we care about/
- see [[https://github.com/TouchPuuhonua/Deep-Rationality][Deep Rationality]]
- Rationality without Deep Rationality is irrational!

Rationality and Deep Rationality work together!

** Rationality Distinctions

The distinctions of /Rationality/ are extremely valuable
- Discovering what Reality offers
- Using valid reasoning about important issues
- Detecting Accidental and Malicious Fallacies
- and so forth

Rationality provides tools for determining if a reasoning process is valid or
invalid and whether, given a degree of confidence in the truth of the premises,
what degree of confidence would be justified in the conclusions.

Study of Rationality and Mathematical Logic which it is based on will reveal
that there's nothing in either which can help us find or form
- our goals
- our values
- our life purpose

The studying of Rationality is directed by our intellect with an awareness of
our emotions.  It is about the /integrity of our thinking/.

We face many challenges to acting Rationally, including
- Lack of awareness of our irrationality
- Insufficient Practice in the Art of Rationality
- Interference from Rhetorical Attacks

** Defense Against the Dark Arts of Rhetoric!

Power hierarchies are maintained by people who skillfully use [[https://en.wikipedia.org/wiki/Rhetoric][Rhetoric]] to
suppress your powers of discernment and manipulate your emotions. They are
trying to use you for their purposes. In their eyes you are
- A Worker-Consumer Unit
- A Subject, rather than a Citizen
- An NPC
- A Tool

This is not a new understanding. The More than 2000 years ago, the great
philosopher [[https://en.wikipedia.org/wiki/Socrates][Socrates]] taught about the misuse of [[https://en.wikipedia.org/wiki/Rhetoric][Rhetoric]] to persuade people to
believe things regardless of the truth of the matter.

Unethical use of Rhetoric is standard in
- Political Speech
- Commercial Marketing
- Where else in our world?

*** The Methods of Rationality are the Defense Against the Dark Arts!

The /Methods of Rationality/ are designed to
- increase your ability to perceive what's going on
- empower you to make your own choices
    - about your life
    - about your future

There are many ways of learning the /Methods of Rationality/. Traditionally
learning the /Methods of Rationality/ has started with studying psychology and
logic and installing the methods into your life through practice.

Further down in /This Document/ you'll find a list of Defense Against the Dark
Arts resources.  Let's begin with an especially awesome resource: HPMOR!

**** HPMOR: Harry Potter and the Methods of Rationality

You can begin your study of the /Methods of Rationality/ enjoyably and powerfully
with [[http://www.hpmor.com][Harry Potter and the Methods of Rationality]], often simply called HPMOR.

Frequently Asked Questions about HPMOR:
- How much does it cost? :: It's free!
- Where can I get it? :: Download it as an =epub=, =mobi= or =pdf= from [[https://github.com/rrthomas/hpmor/releases/tag/v1.2][Github]]
  and read it on your favorite device or read it online at [[http://www.hpmor.com][hpmor.com]].
- Is there a podcast? :: Yes, [[https://hpmorpodcast.com][hpmorpodcast.com]] or [[https://podcasts.apple.com/us/podcast/podcast-the-methods-of-rationality-podcast/id431784580][HPMOR itunes Podcast]].
- Is it available in other languages? :: You'll find translations into at least
  15 languages at [[http://www.hpmor.com/info][hpmor.com/info]]
- If any of those links is bad :: Check [[http://www.hpmor.com][hpmor.com]] for the latest content and links.
- Where did it come from? :: It was written by [[https://www.yudkowsky.net][Eliezer S. Yudkowsky]] who posted
  it to [[https://www.fanfiction.net/s/5782108/1/Harry_Potter_and_the_Methods_of_Rationality][the online FanFiction website]] as he wrote it from 28 February 2010 to 14
  March 2015.
- Do I have to be a Harry Potter Fan to "get" HPMOR? :: No you don't! However,
  for full enjoyment I recommend that you either watch [[https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone_(film)][the first Harry Potter
  Movie]] or read [[https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone][the first Harry Potter book]] before starting HPMOR.
- Do I have to read ALL of HPMOR? :: Eliezer recommends that you /read the first
  ten chapters of HPMOR/ and then decide whether it's for you. If at that point
  you're not "into it", it's probably not the right vehicle for you to learn the
  Methods of Rationality. Fortunately, there are other vehicles!

** Other Resources for Learning and Practicing the Methods of Rationality

The website [[https://www.lesswrong.com][lesswrong.com]] is full of wonderful resources for learning and
practicing the Methods of Rationality, including [[https://www.lesswrong.com/tag/sequences][the Sequences]], a coherent
introduction to Rationality, now also available as part of (another) book by
Eliezer Yudkowsky, [[https://www.lesswrong.com/tag/rationality:-from-ai-to-zombies][Rationality: From AI To Zombies]].

There are a number of excellent resources at the [[https://gregdavidson.github.io/loel][LOEL]] webpage
- [[https://gregdavidson.github.io/loel/loel-media.html][Extraordinary Learners: Books, Texts, Presentations, etc.]]

An excellent new book on Rationality is
- [[https://stevenpinker.com/publications/rationality-what-it-why-it-seems-so-scarce-and-why-it-matters][Rationality: What It Is, Why It Seems Scarce, Why It Matters]]
- by the incomparable [[https://en.wikipedia.org/wiki/Steven_Pinker][Steven Pinker]]

** This is the beginning of the LOEL Curriculum on DATDA

If you like the LOEL approach as described on our [[https://github.com/GregDavidson/loel#readme][LOEL Github Repository]] and the
[[https://gregdavidson.github.io/loel][Original LOEL Website]] and you like the idea of a powerful course on the Methods
of Rationality, please consider joining the team developing this course! You can
begin by getting a Github account and submitting an Issue to the LOEL Repository
or using Github to send a message to the repository owner.
